### PR TITLE
A set of harmless cleanups

### PR DESCRIPTION
**Pull request by lbulej**
This has been split off from the patches that add support for dual loading (as a JVM agent and a native library) to make their review somewhat easier.

### CODE REVIEW

**Comment by vhotspur** [comment]
I will have a look, but first I will try to setup GitHub actions as a replacement for the dead Travis.

**Comment by vhotspur** [comment]
@lbulej Looks good, thanks!

I have merged #13 (build Mac, Linux and Windows all on GitHub actions) so there are two tiny conflicts in `build.xml` (whitespace and some extra `echo`s that are _really_ useful when debugging Windows builds).

Do you want to do a rebase or a merge? Should I do it or you want to do it (do not want to break the subsequent PR too much)?

**Comment by lbulej** [comment]
I'll rebase it. It seems that I have somehow based this PR on #10 which certainly was not the intent and I have no idea how it happened :-) Probably some kind of brain damage...

**Review by vhotspur — APPROVED** [review]

**Comment by lbulej** [comment]
> > It seems that I have somehow based this PR on https://github.com/d-iii-s/java-ubench-agent/pull/10 which certainly was not the intent and I have no idea how it happened :-)

> I thought that was intentional. I think it is worth integrating so, please, feel free to keep it there :-)

OK, I didn't know, because it was original your PR that did not get merged for some time :-) I'll keep it there.

**Comment by lbulej** [comment]
Rebased, including #10. Merging.

**Pull request merged**
